# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run the gemspec command
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = %q{bluplate}
  s.version = "0.0.1"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["matthew jording"]
  s.date = %q{2010-05-23}
  s.description = %q{a simple framework to share yourwork}
  s.email = %q{mjording@opengotham.com}
  s.extra_rdoc_files = [
    "LICENSE",
     "README.rdoc"
  ]
  s.files = [
    ".document",
     ".gitignore",
     "LICENSE",
     "README.rdoc",
     "Rakefile",
     "VERSION",
     "bluplate.gemspec",
     "config/application.yml",
     "init.rb",
     "lib/bluplate.rb",
     "lib/persist.rb",
     "lib/settings.rb",
     "lib/task.rb",
     "lib/ticket.rb",
     "lib/user.rb",
     "spec/bluplate_spec.rb",
     "spec/spec.opts",
     "spec/spec_helper.rb",
     "spec/task_spec.rb",
     "spec/ticket_spec.rb",
     "spec/user_spec.rb"
  ]
  s.homepage = %q{http://github.com/opengotham/bluplate}
  s.rdoc_options = ["--charset=UTF-8"]
  s.require_paths = ["lib"]
  s.rubygems_version = %q{1.3.6}
  s.summary = %q{share your work}
  s.test_files = [
    "spec/bluplate_spec.rb",
     "spec/spec_helper.rb",
     "spec/task_spec.rb",
     "spec/ticket_spec.rb",
     "spec/user_spec.rb"
  ]

  if s.respond_to? :specification_version then
    current_version = Gem::Specification::CURRENT_SPECIFICATION_VERSION
    s.specification_version = 3

    if Gem::Version.new(Gem::RubyGemsVersion) >= Gem::Version.new('1.2.0') then
      s.add_runtime_dependency(%q<settingslogic>, [">= 0"])
      s.add_runtime_dependency(%q<mongo>, [">= 0"])
      s.add_runtime_dependency(%q<tweetstream>, [">= 0"])
      s.add_development_dependency(%q<rspec>, [">= 1.2.9"])
    else
      s.add_dependency(%q<settingslogic>, [">= 0"])
      s.add_dependency(%q<mongo>, [">= 0"])
      s.add_dependency(%q<tweetstream>, [">= 0"])
      s.add_dependency(%q<rspec>, [">= 1.2.9"])
    end
  else
    s.add_dependency(%q<settingslogic>, [">= 0"])
    s.add_dependency(%q<mongo>, [">= 0"])
    s.add_dependency(%q<tweetstream>, [">= 0"])
    s.add_dependency(%q<rspec>, [">= 1.2.9"])
  end
end

